/*
 * generated by Xtext 2.13.0
 */
package com.tmtron.ex.xtext.mlb.tests

import com.google.inject.Inject
import com.tmtron.ex.xtext.mlb.dslB.ModelB
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Test
import org.junit.runner.RunWith

import static org.junit.Assert.*
import org.eclipse.xtext.testing.validation.ValidationTestHelper

@RunWith(XtextRunner)
@InjectWith(DslBInjectorProvider)
class DslBParsingTest {
	@Inject
	ParseHelper<ModelB> parseHelper
	// Helper to test all validation rules and ensure resolved links
	@Inject extension ValidationTestHelper validationTester
	
	@Test def void simpleParsingTest() {
		val parseResult = parseHelper.parse('def fieldB: String;')
		assertNotNull(parseResult)

		// and read the root instance
		val defs = parseResult.definitionsB
		val defA = defs.head
		// ensure it's not null
		assertNotNull(defA)
		assertEquals('fieldB', defA.name)
		parseResult.assertNoErrors
	}
}
