/*
 * generated by Xtext 2.13.0
 */
package com.tmtron.ex.xtext.mla


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DslAStandaloneSetup extends DslAStandaloneSetupGenerated {

	def static void doSetup() {
		new DslAStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
