/*
 * generated by Xtext 2.13.0
 */
package com.tmtron.ex.xtext.mlc.tests

import com.google.inject.Inject
import com.tmtron.ex.xtext.mlc.dslC.ModelC
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import static org.junit.Assert.*
import org.junit.Test
import org.junit.runner.RunWith
import org.eclipse.xtext.testing.validation.ValidationTestHelper

@RunWith(XtextRunner)
@InjectWith(DslCInjectorProvider)
class DslCParsingTest {
	@Inject
	ParseHelper<ModelC> parseHelper
	// Helper to test all validation rules and ensure resolved links
	@Inject extension ValidationTestHelper validationTester
	
	@Test def void simpleParsingTest() {
		val parseResult = parseHelper.parse('def fieldC: Integer;')
		assertNotNull(parseResult)

		// and read the root instance
		val defs = parseResult.definitionsC
		val defA = defs.head
		// ensure it's not null
		assertNotNull(defA)
		assertEquals('fieldC', defA.name)
		parseResult.assertNoErrors
	}
}
