/*
 * generated by Xtext 2.13.0
 */
package com.tmtron.ex.xtext.mlc


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DslCStandaloneSetup extends DslCStandaloneSetupGenerated {

	def static void doSetup() {
		new DslCStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
