/*
 * generated by Xtext 2.13.0
 */
package com.tmtron.ex.xtext.mlb


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DslBStandaloneSetup extends DslBStandaloneSetupGenerated {

	def static void doSetup() {
		new DslBStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
